### ISSUE TITLE
Chest rename bug - can duplicate name_tag item and feature not working

### ISSUE THREAD

**Issue by homerek111** [Gypopo/AutoSellChests#2]
**Description**
AutoSellChests error on clickiing ``NAME_TAG`` icon in chest settings (it's a rename button)
- https://pastebin.com/Mnt4X2MW

you can take away this icon item (duplicate) from gui and name change does not work

**Server version**

server version: ``This server is running Paper version 1.21.1-100-master@20ec622 (2024-09-26T23:53:46Z)``

**Version of EconomyShopGUI**
Chest plugin version: ``2.5.6``
EconomyShopGUI Premium version: ``5.16.4``

**Comment by Gypopo** [comment]
v2.5.7 fixes your issue

**Comment by homerek111** [comment]
> v2.5.7 fixes your issue

thanks! please consider changing chunk loading check to optimize the plugin :)
